include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-campus-auth-guardian
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

PKG_LICENSE:=MIT
PKG_MAINTAINER:=Codex

LUCI_TITLE:=LuCI support for Campus Auth Guardian
LUCI_DEPENDS:=+campus-auth-guardian +luci-compat

include $(TOPDIR)/feeds/luci/luci.mk

