#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

start_service() {
	local enabled
	config_load campus-auth-guardian
	config_get enabled main enabled 0
	[ "$enabled" = "1" ] || return 0

	procd_open_instance
	procd_set_param command /usr/bin/campus-auth-guardian.sh daemon
	procd_set_param respawn 3600 5 0
	procd_set_param file /etc/config/campus-auth-guardian
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger campus-auth-guardian
}

